apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-operated
  namespace: default
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dispatcher-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: dispatcher
  endpoints:
  - port: metrics
    interval: 5s  # Scrape queue depth metrics rapidly every 5 seconds