import os


ML_SERVICE_URL = os.getenv("ML_SERVICE_URL", "http://127.0.0.1:8000")
ML_API_ENDPOINT = f"{ML_SERVICE_URL}/predict"

NUM_WORKERS = int(os.getenv("NUM_WORKERS", "10"))

HTTP_TIMEOUT_SECONDS = float(os.getenv("HTTP_TIMEOUT_SECONDS", "30"))
REQUEST_TIMEOUT_SECONDS = float(os.getenv("REQUEST_TIMEOUT_SECONDS", "60"))

DISPATCHER_METRICS_PORT = int(os.getenv("DISPATCHER_METRICS_PORT", "9000"))

HTTP_MAX_CONNECTIONS = int(os.getenv("HTTP_MAX_CONNECTIONS", "20"))
HTTP_MAX_KEEPALIVE_CONNECTIONS = int(
    os.getenv("HTTP_MAX_KEEPALIVE_CONNECTIONS", "0")
)

WORKER_SLEEP_SECONDS = float(os.getenv("WORKER_SLEEP_SECONDS", "0.0"))
