FROM python:3.11-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir aiohttp git+https://github.com/reconfigurable-ml-pipeline/load_tester.git

COPY load_tester_config/load_tester.py ./load_tester_config/
COPY workload.txt .
COPY imagenet-sample-images/ ./imagenet-sample-images/

ENTRYPOINT ["python", "load_tester_config/load_tester.py"]